// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DentalShopWebApi.Models;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.DAL;

public partial class db_aa382a_ibnsinadentalContext : DbContext
{
    public db_aa382a_ibnsinadentalContext(DbContextOptions<db_aa382a_ibnsinadentalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Maininfo> Maininfos { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Orderprouductlist> Orderprouductlists { get; set; }

    public virtual DbSet<Panner> Panners { get; set; }

    public virtual DbSet<Prouduct> Prouducts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Usersprouduct> Usersprouducts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Notificationid).HasName("pk_notifications");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Orderid).HasName("pk_orders");
        });

        modelBuilder.Entity<Orderprouductlist>(entity =>
        {
            entity.HasKey(e => e.Orderlistid).HasName("pk_orderprouductlists");
        });

        modelBuilder.Entity<Panner>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Prouduct>(entity =>
        {
            entity.HasKey(e => e.Productid).HasName("pk_prouducts");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Userid).HasName("pk_users");
        });

        modelBuilder.Entity<Usersprouduct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_usersprouducts");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}