// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Keyless]
[Table("maininfo")]
public partial class Maininfo
{
    [Column("cairofees")]
    public int? Cairofees { get; set; }

    public int? OutCairoFees { get; set; }
}