// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Table("notifications")]
public partial class Notification
{
    [Key]
    [Column("notificationid")]
    public int Notificationid { get; set; }

    [Column("notificationtext")]
    public string Notificationtext { get; set; }

    [Column("userid")]
    public int? Userid { get; set; }

    [Column("isread")]
    [StringLength(255)]
    [Unicode(false)]
    public string Isread { get; set; }

    [Column("notificationtime")]
    public DateTime? Notificationtime { get; set; }

    [Column("timemark")]
    [StringLength(255)]
    [Unicode(false)]
    public string Timemark { get; set; }
}