// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Table("orderprouductlist")]
public partial class Orderprouductlist
{
    [Key]
    [Column("orderlistid")]
    public int Orderlistid { get; set; }

    [Column("orderid")]
    public int? Orderid { get; set; }

    [Column("prouductid")]
    public int? Prouductid { get; set; }

    [Column("price", TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [Column("amount")]
    public int? Amount { get; set; }
}