// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Table("orders")]
public partial class Order
{
    [Key]
    [Column("orderid")]
    public int Orderid { get; set; }

    [Column("userid")]
    public int? Userid { get; set; }

    [Column("ordertime")]
    public DateTime? Ordertime { get; set; }

    [Column("orderstatus")]
    [StringLength(255)]
    [Unicode(false)]
    public string Orderstatus { get; set; }

    [Column("orderaccepttime")]
    public DateTime? Orderaccepttime { get; set; }

    [Column("orderprice", TypeName = "decimal(10, 2)")]
    public decimal? Orderprice { get; set; }

    [Column("orderlocation")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Orderlocation { get; set; }

    [Column("orderphone")]
    [StringLength(255)]
    [Unicode(false)]
    public string Orderphone { get; set; }

    [Column("paymentmethod")]
    [StringLength(255)]
    [Unicode(false)]
    public string Paymentmethod { get; set; }

    [Column("deliveryfees", TypeName = "decimal(10, 2)")]
    public decimal? Deliveryfees { get; set; }

    [Column("orderexcutetime")]
    public DateTime? Orderexcutetime { get; set; }

    [Column("ordercompletetime")]
    public DateTime? Ordercompletetime { get; set; }

    [Column("useravilabletime")]
    public string Useravilabletime { get; set; }

    [Column("orderamount")]
    public int? Orderamount { get; set; }

    [Column("ordergovernorate")]
    public string Ordergovernorate { get; set; }
    
    [Column("OrderUserName")]
    public string OrderUserName { get; set; }
}