// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Keyless]
[Table("panner")]
public partial class Panner
{
    [Column("link")]
    //[Unicode(false)]
    public string Link { get; set; }

    [Column("id")]
    public int Id { get; set; }
}