// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Table("prouducts")]
public partial class Prouduct
{
    [Key]
    [Column("productid")]
    public int Productid { get; set; }

    [Column("prouductname")]
    public string Prouductname { get; set; }

    [Column("prouductdescription")]
    public string Prouductdescription { get; set; }

    [Column("madein")]
    public string Madein { get; set; }

    [Column("price", TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [Column("amount")]
    public int? Amount { get; set; }

    [Column("exdate")]
    public string Exdate { get; set; }

    [Column("others")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Others { get; set; }

    [Column("firstyear")]
    [StringLength(255)]
    [Unicode(false)]
    public string Firstyear { get; set; }

    [Column("secondyear")]
    [StringLength(255)]
    [Unicode(false)]
    public string Secondyear { get; set; }

    [Column("thirdyear")]
    [StringLength(255)]
    [Unicode(false)]
    public string Thirdyear { get; set; }

    [Column("fourthyear")]
    [StringLength(255)]
    [Unicode(false)]
    public string Fourthyear { get; set; }

    [Column("fifthyear")]
    [StringLength(255)]
    [Unicode(false)]
    public string Fifthyear { get; set; }

    [Column("type")]
    [StringLength(255)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("discount", TypeName = "decimal(10, 2)")]
    public decimal? Discount { get; set; }

    [Column("firstphoto")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Firstphoto { get; set; }

    [Column("secondphoto")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Secondphoto { get; set; }

    [Column("thirdphoto")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Thirdphoto { get; set; }

    [Column("fourthphoto")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Fourthphoto { get; set; }

    [Column("fifthphoto")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Fifthphoto { get; set; }

    [Column("sixthphoto")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Sixthphoto { get; set; }

    [Column("size")]
    public string Size { get; set; }

    [Column("guarantee")]
    public string Guarantee { get; set; }

    [Column("rate")]
    public int? Rate { get; set; }

    [Column("clothes")]
    [StringLength(255)]
    [Unicode(false)]
    public string Clothes { get; set; }

    [Column("teeth")]
    [StringLength(255)]
    [Unicode(false)]
    public string Teeth { get; set; }
}