// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalShopWebApi.Models;

[Table("users")]
public partial class User
{
    [Key]
    [Column("userid")]
    public int Userid { get; set; }

    [Column("username")]
    public string Username { get; set; }

    [Column("useremail")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Useremail { get; set; }

    [Column("userpassword")]
    public string Userpassword { get; set; }

    [Column("userphone")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Userphone { get; set; }

    [Column("userphoto")]
    //[StringLength(2048)]
    //[Unicode(false)]
    public string Userphoto { get; set; }

    [Column("createon")]
    public DateTime? Createon { get; set; }

    [Column("FCMToken")]
    public string FCMToken { get; set; }
}